//
//   Protocol Buffers for Radkov
//
//   Implements a rpc client/server and message
//   format
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: rkpb.proto

package rkpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a generic server response
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rkpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_rkpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_rkpb_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Represents multiple player x & y coordinates
type PlayerPositions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawVectors [][]byte `protobuf:"bytes,1,rep,name=rawVectors,proto3" json:"rawVectors,omitempty"`
}

func (x *PlayerPositions) Reset() {
	*x = PlayerPositions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rkpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerPositions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPositions) ProtoMessage() {}

func (x *PlayerPositions) ProtoReflect() protoreflect.Message {
	mi := &file_rkpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPositions.ProtoReflect.Descriptor instead.
func (*PlayerPositions) Descriptor() ([]byte, []int) {
	return file_rkpb_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerPositions) GetRawVectors() [][]byte {
	if x != nil {
		return x.RawVectors
	}
	return nil
}

var File_rkpb_proto protoreflect.FileDescriptor

var file_rkpb_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x6b, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x72, 0x6b,
	0x70, 0x62, 0x22, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x31,
	0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x61, 0x77, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x72, 0x61, 0x77, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x32, 0x4e, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x15, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x15, 0x2e, 0x72, 0x6b, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x0e, 0x2e, 0x72, 0x6b,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6c, 0x61, 0x6e,
	0x2d, 0x61, 0x63, 0x2e, 0x78, 0x79, 0x7a, 0x2f, 0x61, 0x63, 0x2d, 0x67, 0x61, 0x6d, 0x65, 0x77,
	0x6f, 0x72, 0x78, 0x2f, 0x72, 0x61, 0x64, 0x6b, 0x6f, 0x76, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72,
	0x6b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rkpb_proto_rawDescOnce sync.Once
	file_rkpb_proto_rawDescData = file_rkpb_proto_rawDesc
)

func file_rkpb_proto_rawDescGZIP() []byte {
	file_rkpb_proto_rawDescOnce.Do(func() {
		file_rkpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_rkpb_proto_rawDescData)
	})
	return file_rkpb_proto_rawDescData
}

var file_rkpb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rkpb_proto_goTypes = []interface{}{
	(*Response)(nil),        // 0: rkpb.Response
	(*PlayerPositions)(nil), // 1: rkpb.PlayerPositions
}
var file_rkpb_proto_depIdxs = []int32{
	1, // 0: rkpb.Server.StreamPlayerPositions:input_type -> rkpb.PlayerPositions
	0, // 1: rkpb.Server.StreamPlayerPositions:output_type -> rkpb.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rkpb_proto_init() }
func file_rkpb_proto_init() {
	if File_rkpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rkpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rkpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerPositions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rkpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rkpb_proto_goTypes,
		DependencyIndexes: file_rkpb_proto_depIdxs,
		MessageInfos:      file_rkpb_proto_msgTypes,
	}.Build()
	File_rkpb_proto = out.File
	file_rkpb_proto_rawDesc = nil
	file_rkpb_proto_goTypes = nil
	file_rkpb_proto_depIdxs = nil
}
