// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rkpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerClient interface {
	StreamPlayerPositions(ctx context.Context, opts ...grpc.CallOption) (Server_StreamPlayerPositionsClient, error)
}

type serverClient struct {
	cc grpc.ClientConnInterface
}

func NewServerClient(cc grpc.ClientConnInterface) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) StreamPlayerPositions(ctx context.Context, opts ...grpc.CallOption) (Server_StreamPlayerPositionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Server_ServiceDesc.Streams[0], "/rkpb.Server/StreamPlayerPositions", opts...)
	if err != nil {
		return nil, err
	}
	x := &serverStreamPlayerPositionsClient{stream}
	return x, nil
}

type Server_StreamPlayerPositionsClient interface {
	Send(*PlayerPositions) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type serverStreamPlayerPositionsClient struct {
	grpc.ClientStream
}

func (x *serverStreamPlayerPositionsClient) Send(m *PlayerPositions) error {
	return x.ClientStream.SendMsg(m)
}

func (x *serverStreamPlayerPositionsClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServerServer is the server API for Server service.
// All implementations must embed UnimplementedServerServer
// for forward compatibility
type ServerServer interface {
	StreamPlayerPositions(Server_StreamPlayerPositionsServer) error
	mustEmbedUnimplementedServerServer()
}

// UnimplementedServerServer must be embedded to have forward compatible implementations.
type UnimplementedServerServer struct {
}

func (UnimplementedServerServer) StreamPlayerPositions(Server_StreamPlayerPositionsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPlayerPositions not implemented")
}
func (UnimplementedServerServer) mustEmbedUnimplementedServerServer() {}

// UnsafeServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerServer will
// result in compilation errors.
type UnsafeServerServer interface {
	mustEmbedUnimplementedServerServer()
}

func RegisterServerServer(s grpc.ServiceRegistrar, srv ServerServer) {
	s.RegisterService(&Server_ServiceDesc, srv)
}

func _Server_StreamPlayerPositions_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServerServer).StreamPlayerPositions(&serverStreamPlayerPositionsServer{stream})
}

type Server_StreamPlayerPositionsServer interface {
	Send(*Response) error
	Recv() (*PlayerPositions, error)
	grpc.ServerStream
}

type serverStreamPlayerPositionsServer struct {
	grpc.ServerStream
}

func (x *serverStreamPlayerPositionsServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *serverStreamPlayerPositionsServer) Recv() (*PlayerPositions, error) {
	m := new(PlayerPositions)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server_ServiceDesc is the grpc.ServiceDesc for Server service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Server_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rkpb.Server",
	HandlerType: (*ServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPlayerPositions",
			Handler:       _Server_StreamPlayerPositions_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rkpb.proto",
}
